name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Acuneitx Scan
        run: |
          curl -k -i --request POST --url "https://online.acunetix.com/api/v1/scans" --header "X-Auth: 1986ad8c0a5b3df4d7028d5f3c06e936cd6add1b4da454778961fba97f6eb1568" --header "content-type: application/json" --data '{"profile_id":"11111111-1111-1111-1111-111111111117", "schedule":{"disable":false,"start_date":null,"time_sensitive":false}, "user_authorized_to_scan":"yes", "target_id":"2d60b06a-da1b-4eaf-9547-e91d190659ca"}'
